service: sqs-example

custom:
  settings:
    ACCOUNT_ID: "YOUR_AWS_ACCOUNTID"

provider:
  name: aws
  runtime: nodejs10.x
  region: ew-west-1
  iamManagedPolicies:
    - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
      Resource: "arn:aws:sqs:${self:provider.region}:*:MyQueue"

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
  sqsHello:
    handler: handler.sqsHello
    events:
      - sqs:
          arn:
          batchSize: 1

resources:
  Resources:
    TestQueue:
      Type: "AWS:SQS:Queue"
      Properties:
        QueueName: "TestQueue"
