service: s3-operations-examples

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1
  profile: default

iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "s3:ListBucket"
      - "s3:PutObject"
      - "s3:GetObject"
    Resource: "arn:aws:s3:::wb-s3-example-operations/*"

functions:
  appendText:
    handler: handler.appendText
    events:
      -http:
        path: appendText
        method: put

resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: wb-s3-example-operations
